export const PanelData = [
  {
    id: 'skull',
    title: 'Little Pete Must Die',
    subtitle:
      "During the 1895 San Francisco Fair at Golden Gate Park, hooligan Fong Ching (Little Pete), a city-slicker, police dupe, and stool pigeon, became involved with international kidnapping of Chinese girls from Hong Kong and China to dance at the Park's events. The Arizona Suey Ying Tong men wanted to use the assassination of Little Pete as an unspoken warning to San Francisco's rogue police. Lennie heard from her Father, Chow Chong, that the Suey Ying Tong were involved.",
    imgWidth: '500',
    imgHeight: '500',
    img1: '/images/comic/little-pete/little-pete.png',
    alt1: 'Little Pete',
    img1ClassName: 'w-full h-full object-cover',
    img2: '/images/comic/little-pete/barber.png',
    alt2: 'barber',
    img2ClassName: 'w-full h-full object-cover',
    img3: '/images/comic/little-pete/newspaper.png',
    alt3: 'Newspaper',
    img3ClassName: 'w-full h-full object-cover',
    img4: '/images/comic/little-pete/chinese-new-year.png',
    alt4: 'Chinese New Year',
    img4ClassName: 'w-full h-full object-cover',
    img5: '/images/comic/little-pete/chinese-telephone-company.png',
    alt5: 'Chinese telephone ompany',
    img5ClassName: 'w-full h-full object-fit',
    text1: 'Fong Ching, aka Little Pete.',
    text2:
      'His gangland style murder in a barbershop chair is one of the most infamous crime stories in Chinatown history.',
    text3:
      'San Francisco\'s "Yellow Journalism" news media were forwarned about the impending murder, arriving at the murder scene minutes after the killing.',
    text4:
      'Suey Ying Tong elders told the story that the Tombstone AZ killers chose January 23, 1897, during the Chinese New Year celebration, as the right time to assasinate Little Pete and leave town unnoticed.',
    text5:
      "Albert Bew Chan (Lucretia's grandfather) said that he was the young messanger boy who deliverd the killers message via the Chinatown telephone switchboard.",
    overlay1: 'text-overlay-btm-left-sm',
    overlay2: 'text-overlay-full',
    overlay3: 'text-overlay-top',
    overlay4: 'text-overlay-full',
    overlay5: 'text-overlay-full',
  },
  {
    id: 'beach',
    title: 'The Mystery of China Beach',
    subtitle:
      'The Northwest corner of San Francisco has one of the most scenic beaches in California, if not the world: China Beach. How this lovely place got that name is a bit of a mystery.',
    imgWidth: '500',
    imgHeight: '500',
    img1: '/images/comic/china-beach/china-beach-monument.png',
    alt1: 'China Beach monument',
    img1ClassName: 'w-full h-full object-contain',
    img2: '/images/comic/china-beach/fish-patrol.png',
    alt2: 'Fish patrol',
    img2ClassName: 'w-full h-full object-cover',
    img3: '/images/comic/china-beach/phelan2.png',
    alt3: 'James D Phelan',
    img3ClassName: 'w-full h-full object-cover',
    img4: '/images/comic/china-beach/junk-ship.png',
    alt4: 'Chinese Junk ships',
    img4ClassName: 'w-full h-full object-cover',
    img5: '/images/comic/china-beach/graves.png',
    alt5: 'Cemetary',
    img5ClassName: 'w-full h-full object-cover',
    img6: '/images/comic/china-beach/facility.png',
    alt6: 'New China Beach facility',
    img6ClassName: 'w-full h-full object-cover',
    text1: 'China Beach monument',
    text2: 'The Fish Patrol patrolled the Bay',
    text3: 'James D Phelan',
    text4: 'Chinese Junks',
    text5: 'Cemetary',
    text6:
      'A new $26 million dollar facility is being constructed at the beach',
    overlay1: 'text-overlay-full',
    overlay2: 'text-overlay-full',
    overlay3: 'text-overlay-full',
    overlay4: 'text-overlay-full',
    overlay5: 'text-overlay-full',
    overlay6: 'text-overlay-full',
  },
];
