export const PanelData = [
  {
    id: 'littlePete',
    title: 'Little Pete Must Die',
    subtitle:
      "During the 1895 San Francisco Fair at Golden Gate Park, hooligan Fong Ching (Little Pete), a city-slicker, police dupe, and stool pigeon, became involved with international kidnapping of Chinese girls from Hong Kong and China to dance at the Park's events. \nThe Arizona Suey Ying Tong men wanted to use the assassination of Little Pete as an unspoken warning to San Francisco's rogue police. Lennie heard from her Father, Chow Chong, that the Suey Ying Tong were involved.",
    imgWidth: '500',
    imgHeight: '500',
    img1: '/images/comic/little-pete/little-pete.png',
    alt1: 'Little Pete',
    img1ClassName: 'w-full h-full object-cover',
    img2: '/images/comic/little-pete/barber.png',
    alt2: 'barber',
    img2ClassName: 'w-full h-full object-cover',
    img3: '/images/comic/little-pete/newspaper.png',
    alt3: 'Newspaper',
    img3ClassName: 'w-full h-full object-cover',
    img4: '/images/comic/little-pete/chinese-new-year.png',
    alt4: 'Chinese New Year',
    img4ClassName: 'w-full h-full object-cover',
    img5: '/images/comic/little-pete/chinese-telephone-company.png',
    alt5: 'Chinese telephone ompany',
    img5ClassName: 'w-full h-full object-fit',
    text1:
      'In his 1962 book, "The Hatchet Men", noted historian Richard Dillon described gangster Fong Chine, aka “Little Pete,” as totally amoral who was a Chinatown crime kingpin.',
    text2:
      'His gangland style murder in a barbershop chair is one of the most infamous crime stories in Chinatown history.',
    text3:
      'San Francisco\'s "Yellow Journalism" news media were forwarned about the impending murder, arriving at the murder scene minutes after the killing.',
    text4:
      'Suey Ying Tong elders told the story that the Tombstone AZ killers chose January 23, 1897, during the Chinese New Year celebration, as the right time to assasinate Little Pete and leave town unnoticed.',
    text5:
      "Albert Bew Chan (Lucretia's grandfather) said that he was the young messanger boy who deliverd the killers message via the Chinatown telephone switchboard.",
    overlay1: 'text-overlay-full',
    overlay2: 'text-overlay-full',
    overlay3: 'text-overlay-full',
    overlay4: 'text-overlay-full',
    overlay5: 'text-overlay-full',
  },
  {
    id: 'beach',
    title: 'The Mystery of China Beach',
    subtitle:
      'The Northwest corner of San Francisco has one of the most scenic beaches in California, if not the world: China Beach. \nHow this lovely place got that name is a bit of a mystery. \nThe National Parks Service website states there’s no evidence the Chinese camped there. Historian Eva Ma reported that Chinese Junks were seen anchored there from time to time but with no evidence of fishing. Some speculated that they were pirates.',
    imgWidth: '500',
    imgHeight: '500',
    img1: '/images/comic/china-beach/china-beach-monument.png',
    alt1: 'China Beach monument',
    img1ClassName: 'w-full h-full object-cover',
    text1:
      'In 1981, a well-meaning but not so well informed family erected a monument that assumed fishermen camped there. \nIt celebratd Chinese fishing but unfortunately did not mention that fishermen were barred from fishing in the Bay and were subject to persecution',
    img2: '/images/comic/china-beach/fish-patrol.png',
    alt2: 'Fish Patrol',
    img2ClassName: 'w-full h-full object-fit',
    text2:
      'If a Chinese fishing vessel ventured into the Bay, a group called the Fish Patrol would board, arrest the crew and confiscate any catch. They would then sell the fish for profit. As a young man world famous author Jack London was part of the Fish Patrol and wrote about his exploits',
    img3: '/images/comic/china-beach/james-d-phelan2.png',
    alt3: 'James D Phelan',
    img3ClassName: 'w-full h-full object-fit',
    text3:
      'The cove was originally named Phelan beach after James Phelan who made a large contribution that enabled the State to purchase the property from a private party. Phelan was a notorious racist who persecuted the Chinese. In 1974 when the beach became part of the NPS, it was renamed China Beach',
    img4: '/images/comic/china-beach/junk-ship1.png',
    alt4: 'Chinese Junk ships',
    img4ClassName: 'w-full h-full object-fit',
    text4:
      'Lennie reported that the Clan did make use of the beach. They would anchor there. Though they built campfires there, they had a diVerent mission. Their mission was quite diVerent',
    img5: '/images/comic/china-beach/graves.png',
    alt5: 'Cemetary',
    img5ClassName: 'w-full h-full object-fit',
    text5:
      'The Clan was in the business of exhuming bodies of sojourners who had died in America and returning the remains to the deceased\'s home village. After anchoring at the beach, they would go to a nearby cemetery to “Jub Gwuch” (Pick up bones). In 1880 Robert Louis Stevenson sailed with them. He later wrote about “Skeleton Island” in his famous novel "Treasure Island"',
    img6: '/images/comic/china-beach/new-facility.png',
    alt6: 'New China Beach facility',
    img6ClassName: 'w-full h-full object-fit',
    text6:
      'Eventually China Beach will become a premiere attraction of the Golden Gate National Recreation Area (GGNRA)',
    overlay1: 'text-overlay-full',
    overlay2: 'text-overlay-full',
    overlay3: 'text-overlay-full',
    overlay4: 'text-overlay-full',
    overlay5: 'text-overlay-full',
    overlay6: 'text-overlay-full',
  },
  /*{
    id: 'laundry',
    title: 'Laundries',
    subtitle:
      'Not only was operating a laundry considered a respectable business in Chinatown but the \n*Yee Sang Goon Mo","Laundryman\'s Wife," was classified as the "See How Paw", "Bosswoman". More ambitious laundryman, Yee Sang Goon Bok," were known to select helpmates who could help them build up their business and home-life, somewhat like the pioneer homestead farmers did.',
    imgWidth: '500',
    imgHeight: '500',
    img1: '/images/comic/',
    alt1: '',
    img1ClassName: 'w-full h-full object-cover',
    text1: 'Laundry 1',
    img2: '/images/comic/',
    alt2: '',
    img2ClassName: 'w-full h-full object-fit',
    text2: 'Laundry 2',
    img3: '/images/comic/',
    alt3: '',
    img3ClassName: 'w-full h-full object-fit',
    text3: 'Laundry 3',
    img4: '/images/comic/',
    alt4: '',
    img4ClassName: 'w-full h-full object-fit',
    text4: 'Laundry 4',
    img5: '/images/comic/',
    alt5: '',
    img5ClassName: 'w-full h-full object-fit',
    text5: 'Laundry 5',
    img6: '/images/comic/',
    alt6: '',
    img6ClassName: 'w-full h-full object-fit',
    text6: 'Laundry 6',
    overlay1: 'text-overlay-full',
    overlay2: 'text-overlay-full',
    overlay3: 'text-overlay-full',
    overlay4: 'text-overlay-full',
    overlay5: 'text-overlay-full',
    overlay6: 'text-overlay-full',
  },
  {
    id: 'sailboat',
    title: 'RLS v. Denis the Menace',
    subtitle:
      'While living in San Francisco, part of Stevenson’s daily routine was to visit Portsmouth Square. Chow Chong, who was a teenager at the time, met Stevenson in the square and in a twist, regaled the writer with tales of his family’s seafaring adventures. \nThe Clan befriended him and even took him around to see nearby sights, including the infamous Barbary Coast. Although Stevenson was sickly, he enjoyed the bawdy scenes and wrote about them.',
    imgWidth: '500',
    imgHeight: '500',
    img1: '/images/comic/',
    alt1: '',
    img1ClassName: 'w-full h-full object-cover',
    text1: 'RLS 1',
    img2: '/images/comic/',
    alt2: '',
    img2ClassName: 'w-full h-full object-fit',
    text2: 'RLS 2',
    img3: '/images/comic/',
    alt3: '',
    img3ClassName: 'w-full h-full object-fit',
    text3: 'RLS 3',
    img4: '/images/comic/',
    alt4: '',
    img4ClassName: 'w-full h-full object-fit',
    text4: 'RLS 4',
    img5: '/images/comic/',
    alt5: '',
    img5ClassName: 'w-full h-full object-fit',
    text5: 'RLS 5',
    img6: '/images/comic/',
    alt6: '',
    img6ClassName: 'w-full h-full object-fit',
    text6: 'RLS 6',
    overlay1: 'text-overlay-full',
    overlay2: 'text-overlay-full',
    overlay3: 'text-overlay-full',
    overlay4: 'text-overlay-full',
    overlay5: 'text-overlay-full',
    overlay6: 'text-overlay-full',
  },
  {
    id: 'phone',
    title: 'High Tech Joke Sings',
    subtitle:
      'In 1901, the exchange expanded to a 3 story building at 743 Washington Street, but unfortunately, the building was destroyed in the 1906 earthquake. A new building was built at the same location with a new design that was very ornate. \nAfter the earthquake, city officials sought to move Chinatown to a less desirable location. However, a number of intrepid individuals were able to keep the same location by changing the architecture of new buildings to make Chinatown an exotic-looking location that would attract tourists.',
    imgWidth: '500',
    imgHeight: '500',
    img1: '/images/comic/',
    alt1: '',
    img1ClassName: 'w-full h-full object-cover',
    text1: 'Chinese Telephone Exchange 1',
    img2: '/images/comic/',
    alt2: '',
    img2ClassName: 'w-full h-full object-fit',
    text2: 'Chinese Telephone Exchange 2',
    img3: '/images/comic/',
    alt3: '',
    img3ClassName: 'w-full h-full object-fit',
    text3: 'Chinese Telephone Exchange 3',
    img4: '/images/comic/',
    alt4: '',
    img4ClassName: 'w-full h-full object-fit',
    text4: 'Chinese Telephone Exchange 4',
    img5: '/images/comic/',
    alt5: '',
    img5ClassName: 'w-full h-full object-fit',
    text5: 'Chinese Telephone Exchange 5',
    img6: '/images/comic/',
    alt6: '',
    img6ClassName: 'w-full h-full object-fit',
    text6: 'Chinese Telephone Exchange 6',
    overlay1: 'text-overlay-full',
    overlay2: 'text-overlay-full',
    overlay3: 'text-overlay-full',
    overlay4: 'text-overlay-full',
    overlay5: 'text-overlay-full',
    overlay6: 'text-overlay-full',
  },
  {
    id: 'shingchong',
    title: 'The Merchant',
    subtitle:
      'The story of Louie Wee Lee, Lucretia’s grandfather, was a classic example of the importance of merchant status. He was the founder of a store known as Shing Chong (pronounced “sing charn”).',
    imgWidth: '500',
    imgHeight: '500',
    img1: '/images/comic/',
    alt1: '',
    img1ClassName: 'w-full h-full object-cover',
    text1: 'Shing Chong 1',
    img2: '/images/comic/',
    alt2: '',
    img2ClassName: 'w-full h-full object-fit',
    text2: 'Shing Chong 2',
    img3: '/images/comic/',
    alt3: '',
    img3ClassName: 'w-full h-full object-fit',
    text3: 'Shing Chong 3',
    img4: '/images/comic/',
    alt4: '',
    img4ClassName: 'w-full h-full object-fit',
    text4: 'Shing Chong 4',
    img5: '/images/comic/',
    alt5: '',
    img5ClassName: 'w-full h-full object-fit',
    text5: 'Shing Chong 5',
    img6: '/images/comic/',
    alt6: '',
    img6ClassName: 'w-full h-full object-fit',
    text6: 'Shing Chong 6',
    overlay1: 'text-overlay-full',
    overlay2: 'text-overlay-full',
    overlay3: 'text-overlay-full',
    overlay4: 'text-overlay-full',
    overlay5: 'text-overlay-full',
    overlay6: 'text-overlay-full',
  },
  {
    id: 'cigar',
    title: 'The Cigar Makers',
    subtitle:
      '"Optimo Five Cent Cigars" \n by Lennie Lee \nDuring World War II, when Grandfather Jing Loy Lee and I were young and on a tight budget, we sometimes took slow reminiscing strolls along Commercial Street, from Front to Sansome, once known as the Chinese "Yin Hong,"',
    imgWidth: '500',
    imgHeight: '500',
    img1: '/images/comic/',
    alt1: '',
    img1ClassName: 'w-full h-full object-cover',
    text1: 'The Cigar Makers 1',
    img2: '/images/comic/',
    alt2: '',
    img2ClassName: 'w-full h-full object-fit',
    text2: 'The Cigar Makers 2',
    img3: '/images/comic/',
    alt3: '',
    img3ClassName: 'w-full h-full object-fit',
    text3: 'The Cigar Makers 3',
    img4: '/images/comic/',
    alt4: '',
    img4ClassName: 'w-full h-full object-fit',
    text4: 'The Cigar Makers 4',
    img5: '/images/comic/',
    alt5: '',
    img5ClassName: 'w-full h-full object-fit',
    text5: 'The Cigar Makers 5',
    img6: '/images/comic/',
    alt6: '',
    img6ClassName: 'w-full h-full object-fit',
    text6: 'The Cigar Makers 6',
    overlay1: 'text-overlay-full',
    overlay2: 'text-overlay-full',
    overlay3: 'text-overlay-full',
    overlay4: 'text-overlay-full',
    overlay5: 'text-overlay-full',
    overlay6: 'text-overlay-full',
  },
  {
    id: 'tong',
    title: 'Suey Ying Tong Memories',
    subtitle:
      "There was no mattress on the bed. They were lying on grass mats laid over the wooden planks. Several rectangular-shaped white porcelain blocks served as their pillows. The small room had no closet and only one window that faced the lightwell. \n Two beautiful young Chinese girls dressed in embroidered brocades were sitting among the four men, laughing and lighting their opium pipes for them. The men appeared sleepy and were dressed in drab,gray, rumpled clothing. The men's leathery brown skin over their sunken jaws made a strong contrast to the heavily made-up round, cheek girls.",
    imgWidth: '500',
    imgHeight: '500',
    img1: '/images/comic/',
    alt1: '',
    img1ClassName: 'w-full h-full object-cover',
    text1: 'Suey Ying Tong Memories 1',
    img2: '/images/comic/',
    alt2: '',
    img2ClassName: 'w-full h-full object-fit',
    text2: 'Suey Ying Tong Memories 2',
    img3: '/images/comic/',
    alt3: '',
    img3ClassName: 'w-full h-full object-fit',
    text3: 'Suey Ying Tong Memories 3',
    img4: '/images/comic/',
    alt4: '',
    img4ClassName: 'w-full h-full object-fit',
    text4: 'Suey Ying Tong Memories 4',
    img5: '/images/comic/',
    alt5: '',
    img5ClassName: 'w-full h-full object-fit',
    text5: 'Suey Ying Tong Memories 5',
    img6: '/images/comic/',
    alt6: '',
    img6ClassName: 'w-full h-full object-fit',
    text6: 'Suey Ying Tong Memories 6',
    overlay1: 'text-overlay-full',
    overlay2: 'text-overlay-full',
    overlay3: 'text-overlay-full',
    overlay4: 'text-overlay-full',
    overlay5: 'text-overlay-full',
    overlay6: 'text-overlay-full',
  },
  {
    id: 'cameron',
    title: 'The Donaldina Cameron House',
    subtitle:
      'After more than four decades of all-out cooperative endeavors by honest police, churches, local schools, family associations, and women vigilantes to unshackle the underworld’s vice-hold of ‘White 88 Slavers,‘ ’white slavery ’in Chinatown was at last largely eliminated during the 1930s. \nChinatown female shelter houses, such as Gum Moon on Washington Street and Cameron House, were already quiet places with just a few Chinese ladies, girls, and several elderly white women living there. One of the elderly white women use to give me piano lessons; I asked her why she was living at Cameron House.',
    imgWidth: '500',
    imgHeight: '500',
    img1: '/images/comic/',
    alt1: '',
    img1ClassName: 'w-full h-full object-cover',
    text1: 'The Donaldina Cameron House 1',
    img2: '/images/comic/',
    alt2: '',
    img2ClassName: 'w-full h-full object-fit',
    text2: 'The Donaldina Cameron House 2',
    img3: '/images/comic/',
    alt3: '',
    img3ClassName: 'w-full h-full object-fit',
    text3: 'The Donaldina Cameron House 3',
    img4: '/images/comic/',
    alt4: '',
    img4ClassName: 'w-full h-full object-fit',
    text4: 'The Donaldina Cameron House 4',
    img5: '/images/comic/',
    alt5: '',
    img5ClassName: 'w-full h-full object-fit',
    text5: 'The Donaldina Cameron House 5',
    img6: '/images/comic/',
    alt6: '',
    img6ClassName: 'w-full h-full object-fit',
    text6: 'The Donaldina Cameron House 6',
    overlay1: 'text-overlay-full',
    overlay2: 'text-overlay-full',
    overlay3: 'text-overlay-full',
    overlay4: 'text-overlay-full',
    overlay5: 'text-overlay-full',
    overlay6: 'text-overlay-full',
  },
  */
];
